import {
  LayoutDashboard,
  CalendarDays,
  ClipboardList,
  CheckCircle2,
  FileBarChart,
  Wallet,
  BookOpen,
  Megaphone,
  GraduationCap,
  Users2,
  MessageSquare,
  Library,
  ScrollText,
  Bus,
  BedDouble,
  Receipt,
  AlertCircle,
  Clock,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { RoleConfig } from "./types";

export const ROLE_CONFIGS: Record<string, RoleConfig> = {
  admin: {
    key: "admin",
    name: "EdTech",
    tagline: "Smart Campus ERP",
    basePath: "/dashboard/admin",
    user: { name: "John Admin", role: "Super Admin" },
    nav: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/dashboard/admin" },
      { label: "Students", icon: Users2, href: "/dashboard/admin/students" },
      { label: "Teachers", icon: GraduationCap, href: "/dashboard/admin/teachers" },
      { label: "Attendance", icon: CheckCircle2, href: "/dashboard/admin/academics/attendance" },
      { label: "Examinations", icon: FileBarChart, href: "/dashboard/admin/examinations" },
      { label: "Fees", icon: Wallet, href: "/dashboard/admin/finance" },
      { label: "Library", icon: Library, href: "/dashboard/admin/library" },
      { label: "Transport", icon: Bus, href: "/dashboard/admin/transport" },
      { label: "Hostel", icon: BedDouble, href: "/dashboard/admin/hostel" },
      { label: "Reports", icon: ScrollText, href: "/dashboard/admin/reports" },
    ],
  },
  student: {
    key: "student",
    name: "EdTech",
    tagline: "Smart Campus ERP",
    basePath: "/dashboard/student",
    user: { name: "Aarav Sharma", role: "Student · Class 10-A" },
    nav: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/dashboard/student" },
      { label: "Timetable", icon: CalendarDays, href: "/dashboard/student/timetable" },
      { label: "Assignments", icon: ClipboardList, href: "/dashboard/student/assignments" },
      { label: "Attendance", icon: CheckCircle2, href: "/dashboard/student/attendance" },
      { label: "Results", icon: FileBarChart, href: "/dashboard/student/results" },
      { label: "Fees", icon: Wallet, href: "/dashboard/student/fees" },
      { label: "Library", icon: Library, href: "/dashboard/student/library" },
      { label: "Notices", icon: Megaphone, href: "/dashboard/student/notices" },
    ],
  },
  teacher: {
    key: "teacher",
    name: "EdTech",
    tagline: "Smart Campus ERP",
    basePath: "/dashboard/teacher",
    user: { name: "Priya Nair", role: "Teacher · Mathematics" },
    nav: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/dashboard/teacher" },
      { label: "My Classes", icon: Users2, href: "/dashboard/teacher/classes" },
      { label: "Schedule", icon: CalendarDays, href: "/dashboard/teacher/schedule" },
      { label: "Attendance", icon: CheckCircle2, href: "/dashboard/teacher/attendance" },
      { label: "Assignments", icon: ClipboardList, href: "/dashboard/teacher/assignments" },
      { label: "Marks", icon: FileBarChart, href: "/dashboard/teacher/marks" },
      { label: "Messages", icon: MessageSquare, href: "/dashboard/teacher/messages" },
      { label: "Events", icon: Megaphone, href: "/dashboard/teacher/events" },
    ],
  },
  parent: {
    key: "parent",
    name: "EdTech",
    tagline: "Smart Campus ERP",
    basePath: "/dashboard/parent",
    user: { name: "Suresh Verma", role: "Parent · Aarav S." },
    nav: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/dashboard/parent" },
      { label: "Progress", icon: FileBarChart, href: "/dashboard/parent/progress" },
      { label: "Attendance", icon: CheckCircle2, href: "/dashboard/parent/attendance" },
      { label: "Fees", icon: Wallet, href: "/dashboard/parent/fees" },
      { label: "Messages", icon: MessageSquare, href: "/dashboard/parent/messages" },
      { label: "Notifications", icon: Megaphone, href: "/dashboard/parent/notifications" },
      { label: "Events", icon: CalendarDays, href: "/dashboard/parent/events" },
    ],
  },
  accountant: {
    key: "accountant",
    name: "EdTech",
    tagline: "Smart Campus ERP",
    basePath: "/dashboard/accountant",
    user: { name: "Ramesh Gupta", role: "Accountant" },
    nav: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/dashboard/accountant" },
      { label: "Invoices", icon: Receipt, href: "/dashboard/accountant/invoices" },
      { label: "Payments", icon: Wallet, href: "/dashboard/accountant/payments" },
      { label: "Dues", icon: FileBarChart, href: "/dashboard/accountant/dues" },
      { label: "Defaulters", icon: Users2, href: "/dashboard/accountant/defaulters" },
      { label: "Reports", icon: ScrollText, href: "/dashboard/accountant/reports" },
    ],
  },
  librarian: {
    key: "librarian",
    name: "EdTech",
    tagline: "Smart Campus ERP",
    basePath: "/dashboard/librarian",
    user: { name: "Anita Roy", role: "Librarian" },
    nav: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/dashboard/librarian" },
      { label: "Issue Book", icon: BookOpen, href: "/dashboard/librarian/issue" },
      { label: "Return Book", icon: ClipboardList, href: "/dashboard/librarian/return" },
      { label: "Catalog", icon: Library, href: "/dashboard/librarian/catalog" },
      { label: "Overdue", icon: ScrollText, href: "/dashboard/librarian/overdue" },
      { label: "Fines", icon: Wallet, href: "/dashboard/librarian/fines" },
    ],
  },
  warden: {
    key: "warden",
    name: "EdTech",
    tagline: "Smart Campus ERP",
    basePath: "/dashboard/warden",
    user: { name: "Ramesh Kumar", role: "Hostel Warden" },
    nav: [
      { label: "Dashboard", icon: LayoutDashboard, href: "/dashboard/warden" },
      { label: "Hostel", icon: BedDouble, href: "/dashboard/warden/hostel" },
      { label: "Rooms", icon: ClipboardList, href: "/dashboard/warden/hostel/rooms" },
      { label: "Students", icon: Users2, href: "/dashboard/warden/hostel/students" },
      { label: "Complaints", icon: AlertCircle, href: "/dashboard/warden/hostel/complaints" },
      { label: "Leave", icon: Clock, href: "/dashboard/warden/hostel/leave" },
      { label: "Maintenance", icon: Wrench, href: "/dashboard/warden/hostel/maintenance" },
      { label: "Mess", icon: Receipt, href: "/dashboard/warden/hostel/mess" },
      { label: "Notices", icon: Megaphone, href: "/dashboard/warden/hostel/notices" },
    ],
  },
};

export type { LucideIcon };
