"use client";

import { useState, type ReactNode } from "react";
import { Check, Clock3, Download, ExternalLink, Eye, FileText, ShieldCheck, UserRound } from "lucide-react";
import type { SchoolRole } from "@/components/settings/SettingsPage";
import type { SettingsUser } from "@/components/settings/SettingsPage";

type SectionProps = { currentRole: SchoolRole; user: SettingsUser };
const inputClass = "mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-violet-500 focus:ring-2 focus:ring-violet-100";

function Card({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 className="text-base font-bold">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p><div className="mt-5">{children}</div></section>; }
function Actions({ onCancel }: { onCancel?: () => void }) { const [saved, setSaved] = useState(false); return <div className="mt-6 flex justify-end gap-3 border-t border-slate-100 pt-5"><button onClick={onCancel} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50">Cancel</button><button onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 2000); }} className="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white hover:bg-violet-700">{saved && <Check className="h-4 w-4" />}{saved ? "Saved" : "Save changes"}</button></div>; }
function Toggle({ label, hint, initial = true }: { label: string; hint?: string; initial?: boolean }) { const [enabled, setEnabled] = useState(initial); return <label className="flex cursor-pointer items-start justify-between gap-5 py-3"><span><span className="block text-sm font-medium text-slate-800">{label}</span>{hint && <span className="mt-0.5 block text-xs text-slate-500">{hint}</span>}</span><button type="button" role="switch" aria-checked={enabled} onClick={() => setEnabled(!enabled)} className={`relative mt-0.5 h-6 w-11 rounded-full transition ${enabled ? "bg-violet-600" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${enabled ? "left-6" : "left-1"}`} /></button></label>; }
function Editable({ title, description, children, onCancel }: { title: string; description: string; children: ReactNode; onCancel?: () => void }) { return <><Card title={title} description={description}>{children}</Card><Actions onCancel={onCancel} /></>; }
function SimpleConfiguration({ title, description, toggles }: { title: string; description: string; toggles: Array<{ label: string; hint: string }> }) { return <Editable title={title} description={description}><div className="divide-y divide-slate-100">{toggles.map((toggle) => <Toggle key={toggle.label} {...toggle} />)}</div></Editable>; }

export function ProfileSettings({ user }: SectionProps) { const [name, setName] = useState(user.username); const [email, setEmail] = useState(user.email); const [phone, setPhone] = useState(user.phone ?? ""); const reset = () => { setName(user.username); setEmail(user.email); setPhone(user.phone ?? ""); }; const initials = user.username.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(); return <><Card title="Profile photo" description="This image is shown across Cognora School."><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-full bg-violet-100 text-xl font-bold text-violet-700">{initials}</div><div><button className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold">Upload new photo</button><p className="mt-2 text-xs text-slate-500">JPG, PNG or WebP. Maximum 2 MB.</p></div></div></Card><Editable title="Personal information" description="Keep your details accurate for school communication." onCancel={reset}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Full name<input value={name} onChange={(e) => setName(e.target.value)} className={inputClass} /></label><label className="text-sm font-medium">Email address<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" className={inputClass} /></label><label className="text-sm font-medium">Phone number<input value={phone} onChange={(e) => setPhone(e.target.value)} className={inputClass} /></label><label className="text-sm font-medium">Role<input value={user.role?.role_name ?? ""} readOnly className={`${inputClass} bg-slate-50`} /></label></div></Editable></>; }
export function AccountSecurity(_: SectionProps) { return <><Card title="Account protection" description="Password changes are managed by your school administrator."><div className="divide-y divide-slate-100"><div className="flex items-center justify-between py-3"><div><p className="text-sm font-medium">Password</p><p className="text-xs text-slate-500">Last changed 45 days ago</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600">Managed</span></div><Toggle label="Two-factor authentication" hint="Require a code when signing in from a new device." initial={false} /><Toggle label="Sign-in alerts" hint="Receive an email when your account is accessed." /></div></Card><Editable title="Active sessions" description="Review the devices currently signed in to your account."><div className="rounded-xl border border-slate-200 p-4"><p className="text-sm font-semibold">Chrome on Windows <span className="ml-2 text-xs font-normal text-emerald-600">Current session</span></p><p className="mt-1 text-xs text-slate-500">Bengaluru, India · Active now</p></div></Editable></>; }
export function NotificationPreferences({ currentRole }: SectionProps) { const roleUpdates: Record<SchoolRole, string> = { Admin: "Critical school administration alerts", Teacher: "Class, assignment and timetable updates", Student: "Assignment, result and attendance updates", Parent: "Child attendance, fees and school updates", Librarian: "Overdue books and reservation updates", Accountant: "Payment, invoice and collection updates" }; return <Editable title="Delivery channels" description="Control how we notify you about important updates."><div className="divide-y divide-slate-100"><Toggle label={roleUpdates[currentRole]} hint={`Personalized for your ${currentRole.toLowerCase()} role.`} /><Toggle label="Email notifications" hint="Receive a daily email summary." /><Toggle label="In-app notifications" hint="Show notifications in the Cognora dashboard." /><Toggle label="SMS notifications" hint="Only used for urgent school announcements." initial={false} /></div></Editable>; }
export function AppearancePreferences(_: SectionProps) { return <Editable title="Display preferences" description="Personalize how Cognora School looks and behaves."><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Theme<select className={inputClass} defaultValue="System"><option>System</option><option>Light</option><option>Dark</option></select></label><label className="text-sm font-medium">Language<select className={inputClass} defaultValue="English (India)"><option>English (India)</option><option>Hindi</option></select></label><label className="text-sm font-medium">Date format<select className={inputClass}><option>DD MMM YYYY</option><option>DD/MM/YYYY</option></select></label><label className="text-sm font-medium">Timezone<select className={inputClass}><option>Asia/Kolkata (IST)</option></select></label></div></Editable>; }
export function OrganizationSettings(_: SectionProps) { return <Editable title="School details" description="These details appear on reports, invoices and official communication."><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">School name<input defaultValue="Cognora Public School" className={inputClass} /></label><label className="text-sm font-medium">School code<input defaultValue="CPS-001" className={inputClass} /></label><label className="text-sm font-medium sm:col-span-2">Registered address<input defaultValue="14 Education Lane, Bengaluru, Karnataka 560001" className={inputClass} /></label></div></Editable>; }
export function AcademicConfiguration(_: SectionProps) { return <SimpleConfiguration title="Academic year and curriculum" description="Set defaults used by Academics, Timetable and Examination modules." toggles={[{ label: "Allow teacher lesson-plan edits", hint: "Teachers can update plans for their assigned classes." }, { label: "Show subject codes on timetables", hint: "Include subject identifiers in generated schedules." }]} />; }
export function AttendanceConfiguration(_: SectionProps) { return <SimpleConfiguration title="Attendance rules" description="Configure the workflow for daily attendance." toggles={[{ label: "Allow late attendance marking", hint: "Teachers can submit attendance after the scheduled cutoff." }, { label: "Notify parents for absences", hint: "Send an alert when a student is marked absent." }]} />; }
export function ExaminationConfiguration(_: SectionProps) { return <SimpleConfiguration title="Examination and grading" description="Define result publication and gradebook behaviour." toggles={[{ label: "Publish results after approval", hint: "Students and parents see results only after admin approval." }, { label: "Round marks to two decimals", hint: "Use consistent precision in reports and transcripts." }]} />; }
export function LibraryConfiguration(_: SectionProps) { return <SimpleConfiguration title="Circulation policies" description="Configure defaults for issuing and returning books." toggles={[{ label: "Send overdue reminders", hint: "Notify borrowers before and after their due date." }, { label: "Allow book reservations", hint: "Members can reserve titles already on loan." }]} />; }
export function HostelConfiguration(_: SectionProps) { return <SimpleConfiguration title="Hostel policies" description="Manage resident access and operations." toggles={[{ label: "Require visitor approval", hint: "All visitor entries require hostel office approval." }, { label: "Enable late-return tracking", hint: "Record resident return times after curfew." }]} />; }
export function TransportConfiguration(_: SectionProps) { return <SimpleConfiguration title="Transport operations" description="Configure route visibility and parent alerts." toggles={[{ label: "Share bus arrival alerts", hint: "Notify parents before bus arrival at their stop." }, { label: "Require trip check-in", hint: "Drivers must confirm the beginning of each trip." }]} />; }
export function FinanceConfiguration(_: SectionProps) { return <SimpleConfiguration title="Financial controls" description="Configure defaults for collections and receipts." toggles={[{ label: "Generate receipts automatically", hint: "Create a receipt after each successful payment." }, { label: "Allow partial payments", hint: "Accept fee payments below the outstanding balance." }]} />; }
export function CommunicationTemplates(_: SectionProps) { return <Editable title="Communication defaults" description="Control central communication channels and message templates."><div className="divide-y divide-slate-100"><Toggle label="Email delivery" hint="Allow official school emails to be sent from templates." /><Toggle label="SMS delivery" hint="Enable urgent SMS announcements to approved recipients." /><Toggle label="Template approval workflow" hint="Require administrator approval before a template can be used." /></div></Editable>; }
export function RolesPermissions(_: SectionProps) { const modules = ["Academics", "Attendance", "Timetable", "Examination", "Library", "Hostel", "Transport", "Finance", "Notifications", "Reports", "IAM"]; const roles: SchoolRole[] = ["Admin", "Teacher", "Student", "Parent", "Librarian", "Accountant"]; return <Card title="Roles & permissions" description="Module-access overview. Update the IAM role policy to change permissions."><div className="overflow-x-auto"><table className="min-w-[720px] w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><th className="px-3 py-3">Module</th>{roles.map((role) => <th key={role} className="px-3 py-3 text-center">{role}</th>)}</tr></thead><tbody>{modules.map((module) => <tr key={module} className="border-b border-slate-100"><td className="px-3 py-3 font-medium">{module}</td>{roles.map((role) => { const allowed = role === "Admin" || (module === "Library" && role === "Librarian") || (module === "Finance" && role === "Accountant") || (module === "Notifications" && ["Teacher", "Student", "Parent"].includes(role)); return <td key={role} className="px-3 py-3 text-center">{allowed ? <Check className="mx-auto h-4 w-4 text-emerald-600" /> : <span className="text-slate-300">—</span>}</td>; })}</tr>)}</tbody></table></div><Actions /></Card>; }
export function ReportsExportSettings(_: SectionProps) { return <SimpleConfiguration title="Reports and exports" description="Set controls for reports generated across the school." toggles={[{ label: "Add school logo to exports", hint: "Brand PDF reports, statements and certificates." }, { label: "Require permission for CSV exports", hint: "Restrict data exports to users with assigned report access." }]} />; }
export function AuditActivityLogs(_: SectionProps) { const rows = [["John Admin", "Updated attendance policy", "Today, 10:42 AM"], ["Anita Roy", "Changed library issue limit", "Yesterday, 4:18 PM"], ["System", "Daily backup completed", "Yesterday, 2:00 AM"]]; return <Card title="Audit & activity logs" description="A read-only record of important activity in the school system."><div className="mb-4 flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-xs text-slate-600"><Eye className="h-4 w-4" />This section is read-only. Records cannot be edited or deleted.</div><div className="divide-y divide-slate-100">{rows.map(([actor, action, time]) => <div className="flex items-center gap-3 py-4" key={action}><span className="grid h-9 w-9 place-items-center rounded-full bg-violet-100 text-violet-700"><UserRound className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{action}</p><p className="text-xs text-slate-500">by {actor}</p></div><span className="whitespace-nowrap text-xs text-slate-500"><Clock3 className="mr-1 inline h-3.5 w-3.5" />{time}</span></div>)}</div><button className="mt-5 inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700"><Download className="h-4 w-4" />Export logs</button></Card>; }
export function Integrations(_: SectionProps) { return <Editable title="Connected services" description="Manage external systems connected to Cognora School."><div className="divide-y divide-slate-100"><div className="flex items-center justify-between py-3"><div><p className="text-sm font-medium">Payment gateway</p><p className="text-xs text-slate-500">No provider connected</p></div><button className="text-sm font-semibold text-violet-700">Connect</button></div><div className="flex items-center justify-between py-3"><div><p className="text-sm font-medium">SMS provider</p><p className="text-xs text-slate-500">Configured through secure environment variables</p></div><span className="text-xs font-medium text-emerald-600">Connected</span></div></div></Editable>; }
export function SystemConfiguration(_: SectionProps) { return <SimpleConfiguration title="System controls" description="Global operational settings for Cognora School." toggles={[{ label: "Maintenance mode", hint: "Temporarily show a maintenance screen to non-admin users." }, { label: "Automatic nightly backups", hint: "Run scheduled backups of school data." }]} />; }
